# Generated by Django 4.0.6 on 2022-08-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=64, verbose_name='Center name')),
                ('country', models.CharField(max_length=64, verbose_name='country name')),
                ('city', models.CharField(max_length=64, verbose_name='city name')),
                ('sessions', models.CharField(max_length=64, verbose_name='class name')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='User name')),
                ('class_id', models.CharField(max_length=64, verbose_name='class name')),
                ('subject', models.CharField(max_length=64, verbose_name='subject name')),
                ('class_teacher', models.CharField(max_length=64, verbose_name='class teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64, verbose_name='First name')),
                ('lname', models.CharField(max_length=64, verbose_name='Last name')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='email name')),
                ('location', models.CharField(max_length=64, verbose_name='location')),
                ('occupation', models.CharField(max_length=64, verbose_name='occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64, verbose_name='First name')),
                ('lname', models.CharField(max_length=64, verbose_name='Last name')),
                ('parentEmail', models.CharField(max_length=64, verbose_name='email name')),
                ('class_name', models.CharField(max_length=64, verbose_name='class name')),
                ('reg_no', models.CharField(max_length=64, verbose_name='registration number')),
                ('adm_year', models.CharField(max_length=64, verbose_name='adm_year')),
                ('final_year', models.CharField(max_length=64, verbose_name='final_year')),
                ('age', models.CharField(max_length=64, verbose_name='age')),
                ('gender', models.CharField(max_length=64, verbose_name='gender')),
                ('location', models.CharField(max_length=64, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64, verbose_name='First name')),
                ('lname', models.CharField(max_length=64, verbose_name='Last name')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='email name')),
                ('role', models.CharField(max_length=64, verbose_name='role')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='user name')),
                ('location', models.CharField(max_length=64, verbose_name='location')),
            ],
        ),
    ]
