# Generated by Django 4.0.6 on 2022-08-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='price',
        ),
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='cname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='session',
            field=models.CharField(default='', max_length=255),
        ),
    ]
